/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant;
//import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;  
/**
 *
 * @author Oussama
 */
public class Restaurant_S extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_S
     */
    public Restaurant_S() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_3 = new javax.swing.JPanel();
        txt_C3 = new javax.swing.JTextField();
        jlblTotal8 = new javax.swing.JLabel();
        jlblTax7 = new javax.swing.JLabel();
        jlblSubTotal5 = new javax.swing.JLabel();
        txt_C1 = new javax.swing.JTextField();
        txt_C2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_1 = new javax.swing.JPanel();
        jlblTax4 = new javax.swing.JLabel();
        jlblTax5 = new javax.swing.JLabel();
        jlblSubTotal3 = new javax.swing.JLabel();
        jlblTotal3 = new javax.swing.JLabel();
        jlblTotal4 = new javax.swing.JLabel();
        jlblTotal5 = new javax.swing.JLabel();
        moin_1 = new javax.swing.JButton();
        plus_1 = new javax.swing.JButton();
        plus_2 = new javax.swing.JButton();
        moin_2 = new javax.swing.JButton();
        plus_3 = new javax.swing.JButton();
        moin_3 = new javax.swing.JButton();
        plus_4 = new javax.swing.JButton();
        moin_4 = new javax.swing.JButton();
        moin_5 = new javax.swing.JButton();
        plus_5 = new javax.swing.JButton();
        txt5 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        Panel_2 = new javax.swing.JPanel();
        jlblTax1 = new javax.swing.JLabel();
        jlblTax6 = new javax.swing.JLabel();
        jlblSubTotal4 = new javax.swing.JLabel();
        jlblTotal6 = new javax.swing.JLabel();
        jlblTotal7 = new javax.swing.JLabel();
        plus_6 = new javax.swing.JButton();
        moin_6 = new javax.swing.JButton();
        moin_7 = new javax.swing.JButton();
        plus_7 = new javax.swing.JButton();
        moin_8 = new javax.swing.JButton();
        plus_8 = new javax.swing.JButton();
        moin_9 = new javax.swing.JButton();
        plus_9 = new javax.swing.JButton();
        txt_D2 = new javax.swing.JLabel();
        txt_D3 = new javax.swing.JLabel();
        txt_D1 = new javax.swing.JLabel();
        txt_D4 = new javax.swing.JLabel();
        Panel_5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Recu = new javax.swing.JTextArea();
        Panel_4 = new javax.swing.JPanel();
        txt_T2 = new javax.swing.JTextField();
        txt_T1 = new javax.swing.JTextField();
        txt_T3 = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Panel_6 = new javax.swing.JPanel();
        JTotal = new javax.swing.JButton();
        Receipt = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        txt_C3.setEditable(false);
        txt_C3.setBackground(new java.awt.Color(153, 153, 153));
        txt_C3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_C3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblTotal8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal8.setText("Coût des repas");

        jlblTax7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax7.setText("Coût des boissons");

        jlblSubTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal5.setText("Coût totale");

        txt_C1.setEditable(false);
        txt_C1.setBackground(new java.awt.Color(153, 153, 153));
        txt_C1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_C1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_C1ActionPerformed(evt);
            }
        });

        txt_C2.setEditable(false);
        txt_C2.setBackground(new java.awt.Color(153, 153, 153));
        txt_C2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_C2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("DT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("DT");

        javax.swing.GroupLayout Panel_3Layout = new javax.swing.GroupLayout(Panel_3);
        Panel_3.setLayout(Panel_3Layout);
        Panel_3Layout.setHorizontalGroup(
            Panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTotal8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jlblSubTotal5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_3Layout.createSequentialGroup()
                        .addComponent(jlblTax7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_3Layout.createSequentialGroup()
                        .addComponent(txt_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(Panel_3Layout.createSequentialGroup()
                        .addComponent(txt_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(Panel_3Layout.createSequentialGroup()
                        .addComponent(txt_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        Panel_3Layout.setVerticalGroup(
            Panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(Panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal8)
                    .addComponent(txt_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal5)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
        );

        getContentPane().add(Panel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 390, 180));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Manegement System");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));
        jLabel1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1180, -1));

        Panel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblTax4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTax4.setText("Repas");

        jlblTax5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax5.setText("Panini (4D)");

        jlblSubTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal3.setText("Laibani (6D)");

        jlblTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal3.setText("Pizza (7D)");

        jlblTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal4.setText("HamBurger (5D)");

        jlblTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal5.setText("Sandwichs (4.5D)");

        moin_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_1ActionPerformed(evt);
            }
        });

        plus_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_1ActionPerformed(evt);
            }
        });

        plus_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_2ActionPerformed(evt);
            }
        });

        moin_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_2ActionPerformed(evt);
            }
        });

        plus_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_3ActionPerformed(evt);
            }
        });

        moin_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_3ActionPerformed(evt);
            }
        });

        plus_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_4ActionPerformed(evt);
            }
        });

        moin_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_4ActionPerformed(evt);
            }
        });

        moin_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_5ActionPerformed(evt);
            }
        });

        plus_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_5ActionPerformed(evt);
            }
        });

        txt5.setBackground(new java.awt.Color(102, 102, 102));
        txt5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt5.setForeground(new java.awt.Color(51, 153, 0));
        txt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt5.setText("0");

        txt2.setBackground(new java.awt.Color(102, 102, 102));
        txt2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt2.setForeground(new java.awt.Color(51, 153, 0));
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setText("0");

        txt3.setBackground(new java.awt.Color(102, 102, 102));
        txt3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt3.setForeground(new java.awt.Color(51, 153, 0));
        txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt3.setText("0");

        txt4.setBackground(new java.awt.Color(102, 102, 102));
        txt4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt4.setForeground(new java.awt.Color(51, 153, 0));
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt4.setText("0");

        txt1.setBackground(new java.awt.Color(102, 102, 102));
        txt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt1.setForeground(new java.awt.Color(51, 153, 0));
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("0");

        javax.swing.GroupLayout Panel_1Layout = new javax.swing.GroupLayout(Panel_1);
        Panel_1.setLayout(Panel_1Layout);
        Panel_1Layout.setHorizontalGroup(
            Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_1Layout.createSequentialGroup()
                        .addComponent(jlblTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addComponent(jlblTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTax5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(plus_1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plus_2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plus_3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plus_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(plus_5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moin_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moin_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moin_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moin_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moin_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(Panel_1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jlblTax4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_1Layout.setVerticalGroup(
            Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jlblTax4)
                .addGap(12, 12, 12)
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_1Layout.createSequentialGroup()
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(plus_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moin_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moin_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moin_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel_1Layout.createSequentialGroup()
                                .addComponent(moin_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moin_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_1Layout.createSequentialGroup()
                                .addComponent(plus_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plus_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_1Layout.createSequentialGroup()
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal5)
                            .addComponent(txt1))
                        .addGap(9, 9, 9)
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTax5)
                            .addComponent(txt2))
                        .addGap(9, 9, 9)
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblSubTotal3)
                            .addComponent(txt3))
                        .addGap(7, 7, Short.MAX_VALUE)
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal3)
                            .addComponent(txt4))
                        .addGap(9, 9, 9)
                        .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTotal4)
                            .addComponent(txt5))
                        .addGap(33, 33, 33))))
        );

        getContentPane().add(Panel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 390, 290));

        Panel_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblTax1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTax1.setText("Boissons");

        jlblTax6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax6.setText("Mochito (4D)");

        jlblSubTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal4.setText("Cocktail (5D)");

        jlblTotal6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal6.setText("Citronnade (3D)");

        jlblTotal7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal7.setText("Coca (3D)");

        plus_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_6ActionPerformed(evt);
            }
        });

        moin_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_6ActionPerformed(evt);
            }
        });

        moin_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_7ActionPerformed(evt);
            }
        });

        plus_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_7ActionPerformed(evt);
            }
        });

        moin_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_8ActionPerformed(evt);
            }
        });

        plus_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_8ActionPerformed(evt);
            }
        });

        moin_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/moins.png"))); // NOI18N
        moin_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moin_9ActionPerformed(evt);
            }
        });

        plus_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/plus.png"))); // NOI18N
        plus_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_9ActionPerformed(evt);
            }
        });

        txt_D2.setBackground(new java.awt.Color(102, 102, 102));
        txt_D2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_D2.setForeground(new java.awt.Color(51, 153, 0));
        txt_D2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_D2.setText("0");

        txt_D3.setBackground(new java.awt.Color(102, 102, 102));
        txt_D3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_D3.setForeground(new java.awt.Color(51, 153, 0));
        txt_D3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_D3.setText("0");

        txt_D1.setBackground(new java.awt.Color(102, 102, 102));
        txt_D1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_D1.setForeground(new java.awt.Color(51, 153, 0));
        txt_D1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_D1.setText("0");

        txt_D4.setBackground(new java.awt.Color(102, 102, 102));
        txt_D4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_D4.setForeground(new java.awt.Color(51, 153, 0));
        txt_D4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_D4.setText("0");

        javax.swing.GroupLayout Panel_2Layout = new javax.swing.GroupLayout(Panel_2);
        Panel_2.setLayout(Panel_2Layout);
        Panel_2Layout.setHorizontalGroup(
            Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_2Layout.createSequentialGroup()
                        .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblTax6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblSubTotal4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTotal6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Panel_2Layout.createSequentialGroup()
                                .addComponent(jlblTotal7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28)))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_D2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txt_D3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_D4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_2Layout.createSequentialGroup()
                                .addComponent(plus_6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moin_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_2Layout.createSequentialGroup()
                                .addComponent(plus_7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moin_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_2Layout.createSequentialGroup()
                                .addComponent(plus_8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moin_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_2Layout.createSequentialGroup()
                                .addComponent(plus_9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moin_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel_2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jlblTax1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Panel_2Layout.setVerticalGroup(
            Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_D4))
                    .addGroup(Panel_2Layout.createSequentialGroup()
                        .addComponent(jlblTax1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlblTotal6)
                                .addComponent(txt_D1))
                            .addComponent(moin_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlblTax6)
                                .addComponent(txt_D2))
                            .addComponent(moin_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSubTotal4)
                            .addComponent(moin_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_D3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTotal7)
                            .addComponent(moin_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );

        getContentPane().add(Panel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 400, 290));

        Panel_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        txt_Recu.setEditable(false);
        txt_Recu.setColumns(16);
        txt_Recu.setRows(5);
        jScrollPane1.setViewportView(txt_Recu);

        javax.swing.GroupLayout Panel_5Layout = new javax.swing.GroupLayout(Panel_5);
        Panel_5.setLayout(Panel_5Layout);
        Panel_5Layout.setHorizontalGroup(
            Panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_5Layout.setVerticalGroup(
            Panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Panel_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 350, 550));

        Panel_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        txt_T2.setEditable(false);
        txt_T2.setBackground(new java.awt.Color(153, 153, 153));
        txt_T2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_T2ActionPerformed(evt);
            }
        });

        txt_T1.setEditable(false);
        txt_T1.setBackground(new java.awt.Color(153, 153, 153));
        txt_T1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_T1ActionPerformed(evt);
            }
        });

        txt_T3.setEditable(false);
        txt_T3.setBackground(new java.awt.Color(153, 153, 153));
        txt_T3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_T3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Totale");

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("Taxe");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("Totale sans taxe");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("DT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("DT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("DT");

        javax.swing.GroupLayout Panel_4Layout = new javax.swing.GroupLayout(Panel_4);
        Panel_4.setLayout(Panel_4Layout);
        Panel_4Layout.setHorizontalGroup(
            Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_4Layout.createSequentialGroup()
                        .addComponent(txt_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23))
                    .addGroup(Panel_4Layout.createSequentialGroup()
                        .addGroup(Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_4Layout.createSequentialGroup()
                                .addComponent(txt_T2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(Panel_4Layout.createSequentialGroup()
                                .addComponent(txt_T3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addContainerGap())))
        );
        Panel_4Layout.setVerticalGroup(
            Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax)
                    .addComponent(txt_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_T2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_T3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jlblTotal))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 400, 180));

        Panel_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        JTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTotal.setText("Totale");
        JTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTotalActionPerformed(evt);
            }
        });

        Receipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Receipt.setText("Reçu");
        Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_6Layout = new javax.swing.GroupLayout(Panel_6);
        Panel_6.setLayout(Panel_6Layout);
        Panel_6Layout.setHorizontalGroup(
            Panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(JTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        Panel_6Layout.setVerticalGroup(
            Panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTotal)
                    .addComponent(Receipt)
                    .addComponent(Reset)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 665, 810, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_T1ActionPerformed

    private void txt_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_C1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        SubrClass_Child iExit = new  SubrClass_Child () ;
        iExit.iExitsystem();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
JTextField cleartext = null;

txt1.setText("0");
txt2.setText("0");
txt3.setText("0");
txt4.setText("0");
txt5.setText("0");
txt_D1.setText("0");
txt_D2.setText("0");
txt_D3.setText("0");
txt_D4.setText("0");

for (Component c:Panel_3.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext=(JTextField)c;
        cleartext.setText("");
    }
}

for (Component c:Panel_4.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext=(JTextField)c;
        cleartext.setText("");
    }
}

txt_Recu.setText(null);

    }//GEN-LAST:event_ResetActionPerformed

    private void txt_T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_T2ActionPerformed

    private void JTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTotalActionPerformed
       SubrClass_Child ItemCost = new SubrClass_Child();
       double iTax , iSubTotal , iTotal ;
       
       ItemCost.Meals_1=ItemCost.pMeals_1 * Double.parseDouble(txt1.getText());
       ItemCost.Meals_2=ItemCost.pMeals_2 * Double.parseDouble(txt2.getText());
       ItemCost.Meals_3=ItemCost.pMeals_3 * Double.parseDouble(txt3.getText());
       ItemCost.Meals_3=ItemCost.pMeals_3 * Double.parseDouble(txt3.getText());
       ItemCost.Meals_4=ItemCost.pMeals_4 * Double.parseDouble(txt4.getText());
       ItemCost.Meals_5=ItemCost.pMeals_5 * Double.parseDouble(txt5.getText());
       
       ItemCost.Drinks_1=ItemCost.pDrinks_1* Double.parseDouble(txt_D1.getText());
       ItemCost.Drinks_2=ItemCost.pDrinks_2* Double.parseDouble(txt_D2.getText());
       ItemCost.Drinks_3=ItemCost.pDrinks_3* Double.parseDouble(txt_D3.getText());
       ItemCost.Drinks_4=ItemCost.pDrinks_4* Double.parseDouble(txt_D4.getText());

       iSubTotal=ItemCost.getAmount();
       iTax = ItemCost.cFindTax(iSubTotal);
       iTotal = iSubTotal + iTax;
       
       String Tax =String.format("%.2f",iSubTotal);
       txt_T2.setText(Tax);
        
       String SubTotal =String.format("%.2f",iTax);
       txt_T1.setText(SubTotal);
       
        String Total =String.format("%.2f",iTotal);
       txt_T3.setText(Total);
        
    
       
       String Meal =String.format("%.2f",ItemCost.Meals);
       txt_C1.setText(Meal);
       
        String Drink =String.format("%.2f",ItemCost.Drinks);
       txt_C2.setText(Drink);
       
         String Totals=String.format("%.2f",ItemCost.TotalofMD);
       txt_C3.setText(Totals);
    }//GEN-LAST:event_JTotalActionPerformed

    private void ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptActionPerformed
     int refs =1325 + (int) (Math.random()*4238);
    Calendar timer= Calendar.getInstance();
    timer.getTime();
    SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
     tTime.format(timer.getTime());
      SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
     
     Tdate.format(timer.getTime());
    
    
txt_Recu.append("\tRestaurant Management System  \n\n\n\n" +
     
        "Reference :\t\t"+refs +
        "\n =========================================\n" +
        " Cout de Repas: \t"+txt_C1.getText()+"Dt" +"\n"+
          "Cout de Boissons : \t"+txt_C2.getText() +"Dt"+"\n"+
         "Cout Total: \t\t"+txt_C3.getText()+"Dt" +"\n\n" + 
          "\n ========================================= \n" +
         " Taxe : \t\t"+txt_T1.getText()+"Dt" +"\n" +
         " Total sans taxe  : \t"+txt_T2.getText()+"Dt" +"\n" +
        "Total avec taxe : \t"+txt_T3.getText()+"Dt" +"\n\n" +
        "\n ========================================= \n" +
        "\n Date:"+Tdate.format(timer.getTime()) +
        "\t Time:"+ tTime.format( timer.getTime())+ 
          "\n\n\n \t Merci  \n"
);

 
            
 
    }//GEN-LAST:event_ReceiptActionPerformed

    private void plus_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_1ActionPerformed
   txt1.setText(Integer.toString(Integer.parseInt(txt1.getText())+1));
        // TODO add your handling code here:
    }//GEN-LAST:event_plus_1ActionPerformed

    private void moin_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_1ActionPerformed
   if(Integer.parseInt(txt1.getText())>0) 
   {txt1.setText(Integer.toString(Integer.parseInt(txt1.getText())-1));  }      // TODO add your handling code here:
    }//GEN-LAST:event_moin_1ActionPerformed

    private void plus_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_2ActionPerformed
         txt2.setText(Integer.toString(Integer.parseInt(txt2.getText())+1)); // TODO add your handling code here:
    }//GEN-LAST:event_plus_2ActionPerformed

    private void moin_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_2ActionPerformed
      if(Integer.parseInt(txt2.getText())>0) 
   {txt2.setText(Integer.toString(Integer.parseInt(txt2.getText())-1));  }      // TODO add your handling code here:
    }//GEN-LAST:event_moin_2ActionPerformed

    private void plus_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_3ActionPerformed
   txt3.setText(Integer.toString(Integer.parseInt(txt3.getText())+1)); // TODO add your handling code here:
    }//GEN-LAST:event_plus_3ActionPerformed

    private void moin_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_3ActionPerformed
      if(Integer.parseInt(txt3.getText())>0) 
   {txt3.setText(Integer.toString(Integer.parseInt(txt3.getText())-1));  }    // TODO add your handling code here:
    }//GEN-LAST:event_moin_3ActionPerformed

    private void plus_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_4ActionPerformed
     txt4.setText(Integer.toString(Integer.parseInt(txt4.getText())+1));   // TODO add your handling code here:
    }//GEN-LAST:event_plus_4ActionPerformed

    private void moin_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_4ActionPerformed
     if(Integer.parseInt(txt4.getText())>0) 
   {txt4.setText(Integer.toString(Integer.parseInt(txt4.getText())-1));  }   // TODO add your handling code here:
    }//GEN-LAST:event_moin_4ActionPerformed

    private void plus_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_5ActionPerformed
      txt5.setText(Integer.toString(Integer.parseInt(txt5.getText())+1));  // TODO add your handling code here:
    }//GEN-LAST:event_plus_5ActionPerformed

    private void moin_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_5ActionPerformed
     if(Integer.parseInt(txt5.getText())>0) 
   {txt5.setText(Integer.toString(Integer.parseInt(txt5.getText())-1));  }   // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_moin_5ActionPerformed

    private void plus_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_6ActionPerformed
       txt_D1.setText(Integer.toString(Integer.parseInt(txt_D1.getText())+1));  // TODO add your handling code here:
    }//GEN-LAST:event_plus_6ActionPerformed

    private void moin_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_6ActionPerformed
      if(Integer.parseInt(txt_D1.getText())>0) 
   {txt_D1.setText(Integer.toString(Integer.parseInt(txt_D1.getText())-1));  }    // TODO add your handling code here:
    }//GEN-LAST:event_moin_6ActionPerformed

    private void plus_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_7ActionPerformed
      txt_D2.setText(Integer.toString(Integer.parseInt(txt_D2.getText())+1));   // TODO add your handling code here:
    }//GEN-LAST:event_plus_7ActionPerformed

    private void moin_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_7ActionPerformed
      if(Integer.parseInt(txt_D2.getText())>0) 
   {txt_D2.setText(Integer.toString(Integer.parseInt(txt_D2.getText())-1));  }     // TODO add your handling code here:
    }//GEN-LAST:event_moin_7ActionPerformed

    private void plus_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_8ActionPerformed
           txt_D3.setText(Integer.toString(Integer.parseInt(txt_D3.getText())+1));   // TODO add your handling code here:
   // TODO add your handling code here:
    }//GEN-LAST:event_plus_8ActionPerformed

    private void moin_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_8ActionPerformed
  if(Integer.parseInt(txt_D3.getText())>0) 
   {txt_D3.setText(Integer.toString(Integer.parseInt(txt_D3.getText())-1));  }       // TODO add your handling code here:
    }//GEN-LAST:event_moin_8ActionPerformed

    private void plus_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_9ActionPerformed
         txt_D4.setText(Integer.toString(Integer.parseInt(txt_D4.getText())+1));    // TODO add your handling code here:
    }//GEN-LAST:event_plus_9ActionPerformed

    private void moin_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moin_9ActionPerformed
     if(Integer.parseInt(txt_D4.getText())>0) 
   {txt_D4.setText(Integer.toString(Integer.parseInt(txt_D4.getText())-1));  }     // TODO add your handling code here:
    }//GEN-LAST:event_moin_9ActionPerformed

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException   {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_S().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JTotal;
    private javax.swing.JPanel Panel_1;
    private javax.swing.JPanel Panel_2;
    private javax.swing.JPanel Panel_3;
    private javax.swing.JPanel Panel_4;
    private javax.swing.JPanel Panel_5;
    private javax.swing.JPanel Panel_6;
    private javax.swing.JButton Receipt;
    private javax.swing.JButton Reset;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblSubTotal3;
    private javax.swing.JLabel jlblSubTotal4;
    private javax.swing.JLabel jlblSubTotal5;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTax1;
    private javax.swing.JLabel jlblTax4;
    private javax.swing.JLabel jlblTax5;
    private javax.swing.JLabel jlblTax6;
    private javax.swing.JLabel jlblTax7;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotal3;
    private javax.swing.JLabel jlblTotal4;
    private javax.swing.JLabel jlblTotal5;
    private javax.swing.JLabel jlblTotal6;
    private javax.swing.JLabel jlblTotal7;
    private javax.swing.JLabel jlblTotal8;
    private javax.swing.JButton moin_1;
    private javax.swing.JButton moin_2;
    private javax.swing.JButton moin_3;
    private javax.swing.JButton moin_4;
    private javax.swing.JButton moin_5;
    private javax.swing.JButton moin_6;
    private javax.swing.JButton moin_7;
    private javax.swing.JButton moin_8;
    private javax.swing.JButton moin_9;
    private javax.swing.JButton plus_1;
    private javax.swing.JButton plus_2;
    private javax.swing.JButton plus_3;
    private javax.swing.JButton plus_4;
    private javax.swing.JButton plus_5;
    private javax.swing.JButton plus_6;
    private javax.swing.JButton plus_7;
    private javax.swing.JButton plus_8;
    private javax.swing.JButton plus_9;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JTextField txt_C1;
    private javax.swing.JTextField txt_C2;
    private javax.swing.JTextField txt_C3;
    private javax.swing.JLabel txt_D1;
    private javax.swing.JLabel txt_D2;
    private javax.swing.JLabel txt_D3;
    private javax.swing.JLabel txt_D4;
    private javax.swing.JTextArea txt_Recu;
    private javax.swing.JTextField txt_T1;
    private javax.swing.JTextField txt_T2;
    private javax.swing.JTextField txt_T3;
    // End of variables declaration//GEN-END:variables
}
